---
title: Are survey respondents who have had someone in their home infected by COVID-19 more likely to
disapprove of the way their governor is handling the pandemic?
author: "Your Names Here"
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
library(tidyverse) # if you want more, but still core, toolkit
library(haven)
```

```{r load and clean data, echo=FALSE, warning=TRUE, message=FALSE}
anes_2020 = read_dta("anes_timeseries_2020_stata_20210211.dta")
```


## Importance and Context
<!-- You can (and should delete each of these comments lines in your final report) --> 
<!-- Explain why the reader should care about your research question. -->


```{r}
subsetAnes = anes_2020 %>% 
  filter(V201145 == 1 | V201145 == 2) %>%
  filter(V201624 == 1 | V201624 == 2) %>%
  filter(V201625 == 1 | V201625 == 2) %>%
  mutate(Pass.Fail = ifelse(V201624 == 1 | V201625 == 1, "Covid", "No Covid")) %>%
  select(V201145, V201624, V201625, Pass.Fail)
```

```{r}
table(subsetAnes$V201145)
```

```{r}
table(subsetAnes$V201145,subsetAnes$Pass.Fail)
```


```{r}
t.test(subsetAnes$V201145 ~ subsetAnes$Pass.Fail)
```

## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What are some basic features of the data distribution? --> 
<!-- What changes do you make to the data and why? --> 

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance? --> 